# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\"`\n\tRefStream\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.RefStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_name\"`\n\tValStream\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.ValStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_name\"`\n\tCrdStream\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.CrdStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_name\"f\n\x0cRepSigStream\x12\"\n\x02id\x18\x01 \x01(\x0b\x32\x16.RepSigStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REFSTREAM']._serialized_start=16
  _globals['_REFSTREAM']._serialized_end=112
  _globals['_REFSTREAM_STREAMID']._serialized_start=81
  _globals['_REFSTREAM_STREAMID']._serialized_end=103
  _globals['_VALSTREAM']._serialized_start=114
  _globals['_VALSTREAM']._serialized_end=210
  _globals['_VALSTREAM_STREAMID']._serialized_start=81
  _globals['_VALSTREAM_STREAMID']._serialized_end=103
  _globals['_CRDSTREAM']._serialized_start=212
  _globals['_CRDSTREAM']._serialized_end=308
  _globals['_CRDSTREAM_STREAMID']._serialized_start=81
  _globals['_CRDSTREAM_STREAMID']._serialized_end=103
  _globals['_REPSIGSTREAM']._serialized_start=310
  _globals['_REPSIGSTREAM']._serialized_end=412
  _globals['_REPSIGSTREAM_STREAMID']._serialized_start=81
  _globals['_REPSIGSTREAM_STREAMID']._serialized_end=103
# @@protoc_insertion_point(module_scope)
