name: "SimpleProgram",
operators [
  {
    name: "fiber_lookup",
    id: 10
    fiber_lookup: {
      output_ref {
        id: 9
      },
      output_crd {
        id: 9
      },
      index: "i",
      tensor: "B",
      mode: 0,
      format: "compressed",
      src: true,
      root: true,
    }
  },
  {
    name: "fiber_lookup",
    id: 
    fiber_lookup: {
      output_ref {
        id: 9
      },
      output_crd {
        id: 9
      },
      index: "i",
      tensor: "C",
      mode: 0,
      format: "compressed",
      src: true,
      root: true,
    }
  },
  {
    name: "Union",
    id: 9,
    joiner: {
        join_type: TYPE_UNION,
        input_pairs: [{ 
          crd: {
            id: 2
          },
          crd_label: "crd",
          ref: {
            id: 0
          },
          ref_label: "ref_out-B",
        },
        { 
          crd: {
            id: 0
          },
          crd_label: "crd",
          ref: {
            id: 7
          },
          ref_label: "ref_out-C",
        }],
        output_ref1: {
          id: 6
        }
        output_ref2: {
          id: 8
        }
        output_crd: {
          id: 9
        }
        index: "i"
    }
  }, 
  {
    name: "fiber_write",
    fiber_write: {
        input_crd: { 
          id: 9 
        },
        index: "i",
        tensor: "X",
        mode: 0,
        format: "compressed",
        segsize: "2",
        sink: true,
    }
  }, 
  {
    name: "fiber_lookup",
    fiber_lookup: {
      output_ref {
        id: 9
      },
      output_crd {
        id: 9
      },
      index: "j",
      tensor: "B",
      mode: 1,
      format: "compressed",
      src: true,
      root: true,
    }
  },
  {
    name: "fiber_lookup",
    fiber_lookup: {
      output_ref {
        id: 9
      },
      output_crd {
        id: 9
      },
      index: "j",
      tensor: "C",
      mode: 1,
      format: "compressed",
      src: true,
      root: true,
    }
  },
  {
    name: "fiber_write",
    fiber_write: {
        input_crd: { 
          id: 9 
        },
        index: "j",
        tensor: "X",
        mode: 1,
        format: "compressed",
        segsize: "2",
        sink: true,
    }
  },
  {
    name: "Add",
    alu: {
      vals: {
        inputs: [
          {
            id: 2
          },
          {
            id: 3
          }
        ],
        output: {
            id: 10
        }
      }
      stages: {
        inputs: [
            0, 1
        ],
        output: 0,
        op: ALUOP_SUB,
      }
      output_val: 0
    }
  }
]
