# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stream.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cstream.proto\"`\n\tRefStream\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.RefStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_name\"`\n\tValStream\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.ValStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_name\"`\n\tCrdStream\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.CrdStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_name\"f\n\x0cRepSigStream\x12\"\n\x02id\x18\x01 \x01(\x0b\x32\x16.RepSigStream.StreamID\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x16\n\x08StreamID\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x07\n\x05_nameb\x06proto3'
)




_REFSTREAM_STREAMID = _descriptor.Descriptor(
  name='StreamID',
  full_name='RefStream.StreamID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RefStream.StreamID.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=103,
)

_REFSTREAM = _descriptor.Descriptor(
  name='RefStream',
  full_name='RefStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RefStream.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='RefStream.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REFSTREAM_STREAMID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='RefStream._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=16,
  serialized_end=112,
)


_VALSTREAM_STREAMID = _descriptor.Descriptor(
  name='StreamID',
  full_name='ValStream.StreamID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ValStream.StreamID.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=103,
)

_VALSTREAM = _descriptor.Descriptor(
  name='ValStream',
  full_name='ValStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ValStream.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ValStream.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VALSTREAM_STREAMID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='ValStream._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=114,
  serialized_end=210,
)


_CRDSTREAM_STREAMID = _descriptor.Descriptor(
  name='StreamID',
  full_name='CrdStream.StreamID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CrdStream.StreamID.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=103,
)

_CRDSTREAM = _descriptor.Descriptor(
  name='CrdStream',
  full_name='CrdStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CrdStream.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='CrdStream.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CRDSTREAM_STREAMID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='CrdStream._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=212,
  serialized_end=308,
)


_REPSIGSTREAM_STREAMID = _descriptor.Descriptor(
  name='StreamID',
  full_name='RepSigStream.StreamID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RepSigStream.StreamID.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=103,
)

_REPSIGSTREAM = _descriptor.Descriptor(
  name='RepSigStream',
  full_name='RepSigStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RepSigStream.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='RepSigStream.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REPSIGSTREAM_STREAMID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='RepSigStream._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=310,
  serialized_end=412,
)

_REFSTREAM_STREAMID.containing_type = _REFSTREAM
_REFSTREAM.fields_by_name['id'].message_type = _REFSTREAM_STREAMID
_REFSTREAM.oneofs_by_name['_name'].fields.append(
  _REFSTREAM.fields_by_name['name'])
_REFSTREAM.fields_by_name['name'].containing_oneof = _REFSTREAM.oneofs_by_name['_name']
_VALSTREAM_STREAMID.containing_type = _VALSTREAM
_VALSTREAM.fields_by_name['id'].message_type = _VALSTREAM_STREAMID
_VALSTREAM.oneofs_by_name['_name'].fields.append(
  _VALSTREAM.fields_by_name['name'])
_VALSTREAM.fields_by_name['name'].containing_oneof = _VALSTREAM.oneofs_by_name['_name']
_CRDSTREAM_STREAMID.containing_type = _CRDSTREAM
_CRDSTREAM.fields_by_name['id'].message_type = _CRDSTREAM_STREAMID
_CRDSTREAM.oneofs_by_name['_name'].fields.append(
  _CRDSTREAM.fields_by_name['name'])
_CRDSTREAM.fields_by_name['name'].containing_oneof = _CRDSTREAM.oneofs_by_name['_name']
_REPSIGSTREAM_STREAMID.containing_type = _REPSIGSTREAM
_REPSIGSTREAM.fields_by_name['id'].message_type = _REPSIGSTREAM_STREAMID
_REPSIGSTREAM.oneofs_by_name['_name'].fields.append(
  _REPSIGSTREAM.fields_by_name['name'])
_REPSIGSTREAM.fields_by_name['name'].containing_oneof = _REPSIGSTREAM.oneofs_by_name['_name']
DESCRIPTOR.message_types_by_name['RefStream'] = _REFSTREAM
DESCRIPTOR.message_types_by_name['ValStream'] = _VALSTREAM
DESCRIPTOR.message_types_by_name['CrdStream'] = _CRDSTREAM
DESCRIPTOR.message_types_by_name['RepSigStream'] = _REPSIGSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RefStream = _reflection.GeneratedProtocolMessageType('RefStream', (_message.Message,), {

  'StreamID' : _reflection.GeneratedProtocolMessageType('StreamID', (_message.Message,), {
    'DESCRIPTOR' : _REFSTREAM_STREAMID,
    '__module__' : 'stream_pb2'
    # @@protoc_insertion_point(class_scope:RefStream.StreamID)
    })
  ,
  'DESCRIPTOR' : _REFSTREAM,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:RefStream)
  })
_sym_db.RegisterMessage(RefStream)
_sym_db.RegisterMessage(RefStream.StreamID)

ValStream = _reflection.GeneratedProtocolMessageType('ValStream', (_message.Message,), {

  'StreamID' : _reflection.GeneratedProtocolMessageType('StreamID', (_message.Message,), {
    'DESCRIPTOR' : _VALSTREAM_STREAMID,
    '__module__' : 'stream_pb2'
    # @@protoc_insertion_point(class_scope:ValStream.StreamID)
    })
  ,
  'DESCRIPTOR' : _VALSTREAM,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:ValStream)
  })
_sym_db.RegisterMessage(ValStream)
_sym_db.RegisterMessage(ValStream.StreamID)

CrdStream = _reflection.GeneratedProtocolMessageType('CrdStream', (_message.Message,), {

  'StreamID' : _reflection.GeneratedProtocolMessageType('StreamID', (_message.Message,), {
    'DESCRIPTOR' : _CRDSTREAM_STREAMID,
    '__module__' : 'stream_pb2'
    # @@protoc_insertion_point(class_scope:CrdStream.StreamID)
    })
  ,
  'DESCRIPTOR' : _CRDSTREAM,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:CrdStream)
  })
_sym_db.RegisterMessage(CrdStream)
_sym_db.RegisterMessage(CrdStream.StreamID)

RepSigStream = _reflection.GeneratedProtocolMessageType('RepSigStream', (_message.Message,), {

  'StreamID' : _reflection.GeneratedProtocolMessageType('StreamID', (_message.Message,), {
    'DESCRIPTOR' : _REPSIGSTREAM_STREAMID,
    '__module__' : 'stream_pb2'
    # @@protoc_insertion_point(class_scope:RepSigStream.StreamID)
    })
  ,
  'DESCRIPTOR' : _REPSIGSTREAM,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:RepSigStream)
  })
_sym_db.RegisterMessage(RepSigStream)
_sym_db.RegisterMessage(RepSigStream.StreamID)


# @@protoc_insertion_point(module_scope)
